### ISSUE TITLE
Move ruby version to attributes.rb

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/chef-jellyfish#19]
Please move the Ruby version to the attributes file.

**Comment by calebhearth** [comment]
If it lives in a .ruby-version, it will work better with developer environments like rvm, rbenv, etc. The file can be read pretty easily into the app if needed using `<%= File.read(Rails.root.join(".ruby-version")) %>`, found with the  `RUBY_VERSION` constant, and read from Gemfile.

**Comment by stackus** [comment]
@calebthompson I think here they're talking about taking it out of a chef script and moving it into the chef attributes for a cookbook. This way it can be overridden.

**Comment by chriskacerguis** [comment]
We are, but considering this is for Jellyfish, I like the idea from @calebthompson

**Comment by kmkingsbury** [comment]
Added in 046675c17d9e5384ab64cfd2e10adebc83390267, the ruby version to install is determined by the .ruby-version file in the /home/jellyfish/api directory just like @calebthompson suggested.
