### ISSUE TITLE
Enclose if true statements in single quotes for default.rb recipe

### ISSUE THREAD

**Issue by mcgonagle** [projectjellyfish/chef-jellyfish#36]
The if statements in default.rb need to be wrapped in single quotes
if node['jellyfish']['api']['enabled'] == 'true'
  log 'jellyfish api enabled'
  include_recipe 'chef-jellyfish::api'
end

if node['jellyfish']['ux']['enabled'] == 'true'
  log 'jellyfish ux enabled'
  include_recipe 'chef-jellyfish::ux'
end

**Comment by chriskacerguis** [comment]
We should be using the boolean TRUE.  You will need to adjust the attributes file, and not have the quotes around true.

**Comment by mcgonagle** [comment]
Made change to use boolean true.
