### ISSUE TITLE
Separate common tasks from component specific tasks

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/chef-jellyfish#38]
Looking over things we should separate out common component things (items that both API and UX will need) and move them to default.rb (recipe), then those specific to each one and leave it in api.rb or ux.rb

For example, creating the user "jellyfish" is common to both sets, and should be in default.rb.

**Comment by kmkingsbury** [comment]
Common tasks moved to "_common.rb" recipe, components in own "private" recipe: _nginx, _ruby, _postgres in commit 046675c17d9e5384ab64cfd2e10adebc83390267
